"""Compose a small governance walkthrough from the repository's actual demo captures.

Run: uv run python -m scripts.build_governance_visual
Pillow is already present in the locked FastEmbed dependency tree. No business data
or application UI is generated by this script: only crops, labels and layout.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, ImageOps

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs/demo/governance-workflow.png"
BACKGROUND = "#f5f8f8"
INK = "#12323b"
MUTED = "#50656b"
TEAL = "#237b88"
STEPS = [
    (
        "Current approved answer",
        "Employee sees MOQ 144 units, with citations.",
        "03-grounded-product.png",
        (295, 345, 1245, 910),
    ),
    (
        "New evidence submitted",
        "Admin creates a review item; current facts stay unchanged.",
        "07-controlled-ingestion.png",
        (305, 855, 1090, 1080),
    ),
    (
        "Pending review / decision",
        "Reviewer compares 144 vs 180, then approves or rejects.",
        "08-pending-conflict.png",
        (960, 248, 1835, 854),
    ),
    (
        "Product Master + history",
        "Approval records 180 units; the prior 144 remains in history.",
        "10-master-provenance.png",
        (960, 650, 1835, 1000),
    ),
    (
        "Controlled reindex",
        "Admin completes the background index job.",
        "11-index-updated.png",
        (305, 166, 1845, 448),
    ),
    (
        "Updated grounded answer",
        "Employee now sees 180 units and approved-change evidence.",
        "12-governed-answer.png",
        (298, 268, 1210, 520),
    ),
]


def font(size: int, *, bold: bool = False) -> ImageFont.FreeTypeFont:
    candidates = [
        "Arial Bold.ttf" if bold else "Arial.ttf",
        "DejaVuSans-Bold.ttf" if bold else "DejaVuSans.ttf",
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf"
        if bold
        else "/System/Library/Fonts/Supplemental/Arial.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
        if bold
        else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]
    for candidate in candidates:
        try:
            return ImageFont.truetype(candidate, size)
        except OSError:
            continue
    raise RuntimeError("Install Arial or DejaVu Sans to render the walkthrough")


def wrap(text: str, drawing: ImageDraw.ImageDraw, face: ImageFont.FreeTypeFont, width: int):
    lines: list[str] = []
    for word in text.split():
        if lines and drawing.textlength(f"{lines[-1]} {word}", font=face) <= width:
            lines[-1] += " " + word
        else:
            lines.append(word)
    return lines


def compose(columns: int) -> tuple[Image.Image, list[dict]]:
    rows = len(STEPS) // columns
    canvas = Image.new("RGB", (1600 if columns == 2 else 800, 196 + rows * 466 + 81), BACKGROUND)
    drawing = ImageDraw.Draw(canvas)
    drawing.text((44, 36), "KNOWLEDGE GOVERNANCE", fill=TEAL, font=font(25, bold=True))
    drawing.text(
        (44, 78),
        "From a proposal to an approved answer",
        fill=INK,
        font=font(45 if columns == 2 else 29, bold=True),
    )
    drawing.text(
        (44, 139),
        "Actual Northstar UI captures  /  Fully synthetic business records",
        fill=MUTED,
        font=font(24 if columns == 2 else 17),
    )
    manifest = []
    for index, (title, note, name, box) in enumerate(STEPS):
        column, row = index % columns, index // columns
        x, y = (44 if columns == 2 else 36) + column * 784, 196 + row * 466
        drawing.rounded_rectangle((x, y, x + 728, y + 430), radius=16, fill="white")
        drawing.rounded_rectangle((x + 22, y + 22, x + 77, y + 69), radius=10, fill=TEAL)
        drawing.text(
            (x + 31, y + 29), str(index + 1).zfill(2), fill="white", font=font(28, bold=True)
        )
        drawing.text((x + 91, y + 26), title, fill=INK, font=font(31, bold=True))
        for line_number, line in enumerate(wrap(note, drawing, font(22), 680)):
            drawing.text((x + 22, y + 81 + 27 * line_number), line, fill=MUTED, font=font(22))
        source = ROOT / "docs/demo/screenshots" / name
        with Image.open(source) as frame:
            assert frame.size == (1920, 1080), name
            crop = frame.convert("RGB").crop(box)
        # Preserve every pixel inside the declared crop; never paint over UI text.
        thumbnail = ImageOps.contain(crop, (684, 272), Image.Resampling.LANCZOS)
        canvas.paste(thumbnail, (x + 22, y + 138))
        if columns == 2 and column == 0:
            drawing.line((x + 743, y + 215, x + 767, y + 215), fill=TEAL, width=3)
            drawing.polygon(
                [(x + 767, y + 215), (x + 758, y + 208), (x + 758, y + 222)], fill=TEAL
            )
        manifest.append(
            {
                "step": index + 1,
                "title": title,
                "source": str(source.relative_to(ROOT)),
                "source_sha256": hashlib.sha256(source.read_bytes()).hexdigest(),
                "crop_xyxy": box,
            }
        )
    footer = "Pending or rejected evidence cannot overwrite the current approved fact."
    footer_font = font(26 if columns == 2 else 22, bold=True)
    for line_number, line in enumerate(wrap(footer, drawing, footer_font, canvas.width - 88)):
        drawing.text(
            (44, canvas.height - 70 + line_number * 27), line, fill=INK, font=footer_font
        )
    return canvas, manifest


def main() -> None:
    canvas, manifest = compose(columns=2)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(OUTPUT, optimize=True)
    mobile, _ = compose(columns=1)
    mobile_output = OUTPUT.with_stem(OUTPUT.stem + "-mobile")
    mobile.save(mobile_output, optimize=True)
    (OUTPUT.parent / "governance-workflow.sources.json").write_text(
        json.dumps(
            {
                "output": str(OUTPUT.relative_to(ROOT)),
                "output_sha256": hashlib.sha256(OUTPUT.read_bytes()).hexdigest(),
                "mobile_output": str(mobile_output.relative_to(ROOT)),
                "mobile_output_sha256": hashlib.sha256(mobile_output.read_bytes()).hexdigest(),
                "layout": "Read left to right, then top to bottom; numbered actual UI crops",
                "synthetic_data": True,
                "steps": manifest,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({OUTPUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
